org = "rust-lang"
name = "rustc_codegen_gcc"
description = "libgccjit AOT codegen for rustc"
bots = []

[access.teams]
compiler = "write"
wg-gcc-backend = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = ["success", "success_gcc12", "success_release", "success_failures", "success_m68k", "success_stdarch"]
required-approvals = 0
